// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izofeuelxjujaolgmegg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6b2ZldWVseGp1amFvbGdtZWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjU5MjYsImV4cCI6MjA2MzUwMTkyNn0.e65GwT1KE2I4Mhe_VoKzG2ByVFNcHASa_YwuLP3y3Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});